const fs=require('fs');
const {JSDOM} = require('jsdom');
const html=fs.readFileSync('client/print-preview.html','utf8');
const css=fs.readFileSync('client/print-preview.css','utf8');
const dom=new JSDOM(html,{resources:'usable',runScripts:'dangerously'});
const {window}=dom;
const style=window.document.createElement('style');style.textContent=css;window.document.head.appendChild(style);
window.document.body.innerHTML+='<div class=\'page\' id=\'test\'></div>';
const comp=window.getComputedStyle(window.document.getElementById('test'));
console.log('width',comp.width,'height',comp.height);
